### ISSUE TITLE
issues with keefox/keebird since thunderbird 52

### ISSUE THREAD

**Issue by eseb63** [kee-org/keebird#3]
the issues were initially documented [here](https://github.com/kee-org/KeeFox/issues/814) 

copy of the initial post:
======
hello,

i use portable editions of thunderbird (52.3.0) and Keepass (2.36) with keefox 1.7.2.

i have problems since thunderbird version 52.0 :

- the authentification popup layout is broken : buttons are nearly entirely hidden
![screenshot-2018-5-6 kee-org keefox](https://user-images.githubusercontent.com/31894250/39674571-2092cab2-514e-11e8-9b0f-33616f84ae5e.png)

- keefox doesn't launch keepass anymore if a relative path is specified in the options (it works with an absolute one) ; these problems don't occur with thunderbird 45.8 and older
- when clicking the browse button (for example keepass tab in the options) the specified relative path is ignored.

these relative path problems exist also with Firefox since a few months so it seems to be a global issue with relative path handling ?

======

thanks in advance  for fixing...

eseb63

**Comment by dlech** [comment]
One GitHub issue per problem please. Authentication dialogs should be fixed by 293ff7c163fba2ed634fe22913740f545782badb (not released yet). The other issues are new to me.

Also, if the relative path issue also occurs in Firefox with Kee 2.x, then be sure to open an issue at https://github.com/kee-org/browser-addon/issues too since these are separate plugins now.

**Comment by dlech** [comment]
I've just released v1.0.0 that should fix the password dialog box issue. Please open new issues if any of the other reported problems exist in this version.

https://github.com/kee-org/keebird/releases/tag/v1.0.0
